name: Triggers!!
run-name: Â¡Actions con triggers schudle, workflow_dispacht y push !
on:
  schudle:
    - cron: '50 23 30 6 *'
  push:
    branches: 
      - 'main' 
      - 'release/**'
    paths:
      '**.py'
  workflow_dispacht:
  inputs:
    lenguaje_favorito:
      description: 'Lenguaje preferiod'
      default: python
      required: true
      type: choice
      options:
      - javascript
      - python
      - java
    nombre:
      description: 'Tu nombre'
      required: true
      default: yosuad
      type: string

jobs:
    hola-mundo-manual:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Definir nombre
          run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
        - name: Definir lenguaje
          run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
        - name: Correr script
          run: python hola_lenguaje.py
    hola-mundo:
      if: ${{ github.event_name != 'workflow_dispatch' }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Definir variable
          run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
        - name: Correr script
          run: python hola_mundo.py
