name: Aprendiendo GIT-HUB Actions con triggers!!

run-name: ${{ github.event_name }} ejecutado por ${{ github.actor }}

on:
  # ðŸ•’ Trigger programado
  schedule:
    - cron: '50 23 30 6 *' # Ojo: junio solo tiene 30 dÃ­as

  # ðŸš€ Trigger por push
  push:
    branches:
      - 'main'
      - 'release/**'
    paths:
      - '**.py'

  # ðŸ”˜ Trigger manual desde la interfaz de GitHub
  workflow_dispatch:
    inputs:
      alerta:
        description: 'Nivel de alerta'
        required: true
        default: 'medio'
        type: choice
        options:
          - bajo
          - medio
          - alto

jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar informaciÃ³n
        run: 
          echo "Evento: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Nivel de alerta: ${{ github.event.inputs.alerta }}"
