name: Triggers!!
run-name: ¡Actions con triggers schudle, workflow_dispacht y push !
on:
  schudle:
    - cron: '50 23 30 6 *'
  push:
    branches: 
      - 'main' 
      - 'release/**'
    paths:
      '**.py'
  workflow_dispacht:
  inputs:
    lenguajes:
      description: 'Lenguaje preferiod'
      default: javascript
      required: true
      type: choice 
      options:
      - javascript
      - python
    nombre:
      description: 'Tu nombre'
      required: true
      type: Juan

jobs:
  ejemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar información
        run: 
          echo "Evento: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Nivel de alerta: ${{ github.event.inputs.alerta }}"